---
- name: Create ssh keys
  hosts: localhost
  vars_files:
    - {{ playbook_dir + '/vars.yaml' }}
  
  tasks:
  - name: Create ssh keys for master nodes
    community.crypto.openssh_keypair:
      path: "{{ ansible_master_ssh_key_path + 'master' }}"
      size: 2048  
      register: master_key
  - name: Create ssh keys for worker nodes
    community.crypto.openssh_keypair:
      path: "{{ ansible_worker_ssh_key_path + 'worker' }}"
      size: 2048
      register: worker_key


